### ISSUE TITLE
Nothing Seems to work as it was described

### ISSUE THREAD

**Issue by dleaf** [ZachSaucier/Just-Read#242]
Really love the app ... promising features but unfortunately it is not working for me now for some reason. I'm on MacOS 10.14.3 with Chrome Version 73.0.3683.86 (Official Build) (64-bit) and the Premium version of JR. 
Here is a quick video of what's happening: https://www.useloom.com/share/0c2b4710a69c48df924d2fa73a97f4dd

Basically two main issues: 1- When I click share, there is no way for me to copy the link or select it .. it shows there 
2- The customization menu as shown isn't showing properly .. when I select the dark theme, nothing happens. 

Am I missing anything or are these just bugs

**Comment by ZachSaucier** [comment]
I'm sorry to hear that! 

Are these errors occurring on every page that you try or only some?

Can you please open up the console (F12) and tell me what it says?

**Comment by ZachSaucier** [comment]
On [the page you show in the video](https://www.hometalk.com/41413412/5-best-bedroom-color-palettes-according-to-psychology) the visual style editor buttons are a bit wonky due to their over-eager site styling (a known issue on some pages) but they still work for me. I also am able to share the Just Read version of a page and switch between themes just fine on my side. I need more information to figure out what's going on for you. 

Can you please also show me a screenshot of what your "additional settings" under [Just Read's Options](chrome-extension://dpamdgmnffodphoamchpmbclkpmccjga/options.html) are?

**Comment by dleaf** [comment]
Thank you for your reply … If the styling works shouldn’t the dark theme apply anyways .. I have selected the dark theme and nothing happen… also, in many cases the function stoped working and I had to close chrome and restart it (check video out: https://dsc.cloud/Dleaf/Screen-Recording-2019-03-25-13-47-47.mp4). 


On another note, I truly believe that JustRead app has a great potential … As a marketer and can, I can easily see the potential, what are you doing to get more customers? I will be happy to provide you with some marketing directions and possibly help you turn this app into true money making machine :) 


Lastly, I will see if one of our designers can work on an icon for you :) free of charge … don’t take me up on this just yet, let me clear it first.

**Comment by ZachSaucier** [comment]
I cannot understand how these bugs are occurring because you're not leaving me with any information about how to recreate them, information about the errors, or even information about your Just Read settings. Until you provide me information like what I asked for above, I can't help fix these errors.

**Comment by dleaf** [comment]
I'm not sure why your emails didn't show up in my main inbox.. Anyways, I have submitted the requested info before and not sure why you haven't been able to see them... Here are they again:

- Environment screenshots (settings, browser version and OS): https://dsc.cloud/Dleaf/JR-screenshots.zip
- This video shows the the button becomes irresponsive and have to restart browser for to work again (until it stops working again)  https://dsc.cloud/Dleaf/Screen-Recording-2019-03-25-13-47-47.mp4
- This video shows you that styling is missed up and doesn't work anyways even if I try https://www.useloom.com/share/0c2b4710a69c48df924d2fa73a97f4dd
- Same video shows that I'm not able to copy sharing URL 
- Same video I performed other functions for you to see how they work so I have an idea about the experience

**Comment by ZachSaucier** [comment]
Based on your screenshot, the dark stylesheet has been replaced by the original stylesheet. Please copy the [dark styles](https://github.com/ZachSaucier/Just-Read/blob/master/dark-styles.css) into the dark styles file (If you want to change the original file, not the copy, you can remove the `locked` class from the HTML element using your developer tools). 

As for the sharing issue, you still need to answer my question: does the issue happen for you on every page? or just that one? 

I also still would like to see any errors happening in the console on problematic pages, which can be viewed by pressing F12.

**Comment by ZachSaucier** [comment]
Seeing your "Additional options" settings may also aid me in helping you.

**Comment by dleaf** [comment]
Additional options is already in the sent zip link ... here it is again as a link (no option to upload here)
https://dsc.cloud/Dleaf/Screen-Shot-2019-03-28-at-11.18.58-PM.png

Issue happens on all pages ... is this what you want to see:
https://dsc.cloud/Dleaf/Screen-Shot-2019-03-29-at-2.03.23-PM.png

**Comment by ZachSaucier** [comment]
Yes, that's the correct screen but there are no errors about Just Read on there... Can you try keeping that tab open, load an article page, clear that window (using the 🚫 in the top left of the window), run Just Read including trying to share a page, then take a screen shot of any errors that appear?

**Comment by dleaf** [comment]
https://www.useloom.com/share/731705890f044c5893de9269fffc301e
Is this what you need?

**Comment by ZachSaucier** [comment]
Yes, thanks! I was able to figure out that the URL (https://justread.link/cRv-Thm5j) works correctly. So I determined it must be a problem with how JRP is interpreting the settings. After looking I realized that I didn't add a default state for the option relating to automatically opening the shared page in the most recent version of JRP where I changed these settings some. 

Being unable to manually select the URL was a separate issue due to a `user-selection: none` line that I must have added sometime recently (I don't remember doing that). 

I have now fixed both of these issues and it should work properly as of JRP version 3.4.2. Let me know if it doesn't.

P.S. You can view pages you've shared by going to https://justread.link/dashboard

**Comment by dleaf** [comment]
That seem to resolve all major issues ...  
√ — I have replaced the dark theme as instructed and it worked. 
√ — Shareable link is working great

I still have the occasional not responding issue (when I click the icon nothing happens) so I have to restart the browser
Theme changing still looks scrambled and overtime I switch between dark and light, a new copy of css file gets created.  
I also got a new error saying that I have exceeded the 100 limit and when I checked it wasn't 

Anyways, those are issues easier to live with :)

**Comment by ZachSaucier** [comment]
If you click Just Read and it doesn't start its likely an issue with the specific page or an installed extension. It would be helpful to know if it regularly occurs on the same page(s) and what error(s) are associated with it not working. I would highly doubt you need to restart Chrome all the way to get it working again, but this could be true. 

The default light and dark themes are meant to never be edited, so any time you attempt to do so it will create a new copy of the theme. This is true anytime you click "Save and close" (to just switch between existing themes, use the drop down and then click "Close without saving"). 

What did the error saying you have exceeded the 100 shared article limit look like? I'm guessing it was just a bad load where the stylesheet failed to load for some reason...
