### ISSUE TITLE
Auto-run not working.

### ISSUE THREAD

**Issue by Orlinky** [ZachSaucier/Just-Read#278]
**Describe the bug**
A couple hours ago i noticed that auto-run stopped working.

**Please complete the following information:**
 - OS: macOS Catalina 10.15.1
 - Browser: Chrome 
 - Version 78.0.3904.108

**Additional context**
I can still enter reader view if manually activate it by clicking on the extension's icon. My settings have not changed since the last time i used the extension. I tried uninstalling and reinstalling and the problem remains.

**Comment by ZachSaucier** [comment]
Hey Orlinky, sorry you're having some trouble. 

Can you try adding text.npr.org to your auto-run list and seeing if https://text.npr.org/ causes Just Read to auto-run? Are there any errors in your browser's console (F12 to view console)?

**Comment by Orlinky** [comment]
Hey, thank you for your time.

I did what you suggested and it doesn't work and there are no errors in the console.

**Comment by ZachSaucier** [comment]
After some more testing I realized this was introduced when I was trying to reduce the permissions in 8c91009, the most recent commit. I didn't catch it because I just figured out that I didn't hard refresh my system. Sorry about that! It should be fixed in the latest version that I'm pushing now. Your system should update soon.

**Comment by Orlinky** [comment]
I just tried the new 2.0.7 version and it is still not working on my end, am i missing something?

**Comment by ZachSaucier** [comment]
Nope, I made a dumb mistake. Fixed it now. Pushing again.

**Comment by Orlinky** [comment]
Everything is back to normal, thank you!
