### ISSUE TITLE
Useless vertical scrollbar image is always printed next to article title

### ISSUE THREAD

**Issue by dmgirard** [ZachSaucier/Just-Read#354]
**Describe the bug**
When I go to print an article, a useless vertical scrollbar image is always printed to the right of the article title. This gives readers the false impression that there is more to the title than what is being displayed. It should be eliminated. 

**To Reproduce**
1. Go to 'https://www.empoweringparents.com/article/responses-backtalk-excuses/'
2. Click on the 'Just Read' extension button
3. Click on the 'Print' button.
4. Notice vertical scrollbar to the right of the article's title. 

**Expected behavior**
No vertical scrollbar should be displayed. 

**Screenshots**
![scrollbar](https://user-images.githubusercontent.com/78242890/106476943-9c3b1100-6475-11eb-934f-708a5216d245.png)

**Please complete the following information:**
 - OS: Microsoft Windows 10
 - Browser: Google Chrome 
 - Version: Version 88.0.4324.104 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by ZachSaucier** [comment]
Hey dmgirard. I again cannot reproduce this issue. Any other information as to how to reproduce the issue? Do you have any custom zoom settings or something like that?

**Comment by dmgirard** [comment]
I removed all other extensions and the problem persisted. Zoom is not on. Appearance settings all seem normal to me. The display resolution is a bit low by modern standards but I doubt that would be causing an issue.

![2021-02-01 15_27_53-Settings](https://user-images.githubusercontent.com/78242890/106514592-724c1380-64a2-11eb-8c63-a26067f3a755.png)

![2021-02-01 15_27_05-Settings](https://user-images.githubusercontent.com/78242890/106514579-6ceec900-64a2-11eb-9fb8-d21e34ae46af.png)

**Comment by ZachSaucier** [comment]
If you're willing to do a screenshare with me to see if I can figure out where the issue is coming from please email me at support@justread.link. Otherwise I'm going to close this as a not reproduceable.

**Comment by dmgirard** [comment]
Let's do it. I can screenshare now.

Doug

**Comment by dmgirard** [comment]
Do you have a private email address that we can message back and forth on?

Doug

**Comment by ZachSaucier** [comment]
Should be fixed in the next Just Read version which I'll push to the store now.

**Comment by dmgirard** [comment]
That worked. Thanks.

**Comment by rfog** [comment]
It is happening to me. Scroll bars are horrid. It happens with my custom CSS, but strangely it is not only a thing. It is related to line "text-align: justify;" in p section, but removing it does not resolve the issue. If I remove all of this:

`p {
    line-height: 1.1;
    font-size: 17px;
    text-align:	justify;	
}

h1 {
    font-family: 'Source Sans Pro', sans-serif;
    font-weight: 700;
    font-size: 1.875em;
    line-height: 1.125;
}

h2 {
    font-family: 'Source Sans Pro', sans-serif;
    font-weight: 700;
    font-size: 1.45em;
    line-height: 1.2625em;
}

h3 {
    font-family: 'Merriweather', serif;
    font-size: 1.25em;
    line-height: 1.5;
}

hr {
    height: 1px;
    background-color: #D8D8D8;
    border: none;
    width: 100%;
    margin: 0px;
}`

it removes the scroll bars. Then addling section by section, the scrollbars do not appear until suddenly appear. It is a very strange issue.

I'm attaching the entire CSS plus a capture of the printing. This happens in Edge Chromium Version 116.0.1938.81 (Official build) (64-bit), and in this page as sample (I've tested in others and happens the same): https://culturacientifica.com/2023/09/13/las-matematicas-del-bordado-sashiko/


[PrintThisCustom.zip](htt
<img width="538" alt="Screenshot 2023-09-13 160551" src="https://github.com/ZachSaucier/Just-Read/assets/1958131/6e26978d-b5d4-40e2-8304-700ae214ef14">
ps://github.com/ZachSaucier/Just-Read/files/12598466/PrintThisCustom.zip)

**Comment by ZachSaucier** [comment]
Hey @rfog. I'm having trouble understanding the issue.

> It happens with my custom CSS, but strangely it is not only a thing.

So does it happen with the default theme (i.e. not custom CSS)?

> It is related to line "text-align: justify;" in p section, but removing it does not resolve the issue.

How do you know it's related if removing it doesn't resolve the issue?

**Comment by rfog** [comment]
Zach, sorry to be not clear enough.

With default CSS it does not happen, it happens only with mine. 

I will try to explain better. Start with my attached CSS. You see the scrollbars in the print preview. Then remove the justify line only. Scrollbars are still in printing preview. Now remove p, h1, h2, h3, pr sections. The scrollbars are gone. Now put back the removed p, h1, h2, h3, pr sections without the justify line. Still no scrollbars. Put back the justify line and... scrollbars. Now you can start over by removing the justify line in p section. 

The problem is if the justify line is causing the scrollbars, why is it needed to remove all p, h1, h2, h3, pr sections and then put them back? Why do scrollbars not simply disappear when removing the justify line and it is needed to entirely remove all other sections? 

BTW, what I want is justify with hyphenation.

**Comment by rfog** [comment]
BTW, my custom CSS works fine in last version of Firefox under Windows but not in last version of Chrome in Windows.

**Comment by ZachSaucier** [comment]
Hey @rfog. Unfortunately debugging custom stylesheets isn't really in scope for support. I will say that when I add the styles that you shared to the default stylesheet on Chrome for Windows and for Mac it's not an issue.

**Comment by rfog** [comment]
Yes, it is what I was to write here: adding my customizations for justify, hyphen, p section and center images and headers does not break the standard style, and it is what I've done.

BTW, now I'm a paid customer, not for the support or the extra stuff that I'm not using, but to pay for good tools. After testing a zillion of these kinds of tools IMHO yours is the best.

**Comment by ZachSaucier** [comment]
Thanks for supporting Just Read!!
